import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sound Guessr App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-cover bg-center bg-repeat w-screen h-screen font-serif"
        style={{ backgroundImage: "url('/wood-bg-100.png')" }}
      >
        {children}
      </body>
    </html>
  );
}
